---
title: ""
author: ""
date: ""
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    theme: cerulean
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(ggpubr)
library(gridExtra)
library(grid)
library(cowplot)
library(reactable)
library(data.table)
library(reticulate)
library(sciplot)
library(plotly)
library(matrixStats)
library(SummarizedExperiment)
library(RColorBrewer)
library(heatmaply)
library(ggrepel)
library(tidyverse)
library(gprofiler2)
library(patchwork)
library(DESeq2)
library(apeglm)
library(fgsea)
library(msigdbr)
library(compiler)
library(shiny)
library(tippy)
library(msigdbr)
library(GSVA)
library(pals)
library(ggtext)
library(broom)
library(DT)
#load RData
load("~/Documents/Q005841_HNSCC/work/processed_dat/dds_Dec2021_hnscc.RData")
load("~/Documents/Q005841_HNSCC/work/processed_dat/rld_hnscc_Dec2021.RData")
```
# Cal27: NSD2.KO vs NSD1.KO {.tabset .tabset-pills}
```{r include= FALSE}
volc <- function(r, x, y, ylab, ttl) {
  d <- as.data.frame(r) %>%
    dplyr::rename(x = !!x, y = !!y) %>%
    mutate(kind = case_when((abs(x) > 2 & y < .05) ~ 'DE',
                            abs(x) > 2 ~ '|logFC|>2',
                            y < .05 ~ 'FDR<0.05',
                            T ~ 'NS'),
           y = -log10(y))
  ct <- d %>% 
    dplyr::filter(kind == 'DE') %>%
    mutate(up = x > 0) %>%
    dplyr::count(up) %>%
    mutate(x = ifelse(up, Inf, -Inf),
           y = Inf,
           h = as.numeric(up))
  ggplot(d, aes(x, y, color = kind)) +
    geom_vline(xintercept = c(-2, 2), linetype = 'dashed') +
    geom_hline(yintercept = -log10(0.05), linetype = 'dashed') +
    geom_point(alpha = .5) +
    geom_label(aes(x = x, y = y, label = n, hjust = h),
              vjust = 1, data = ct, inherit.aes = F) +
     geom_text_repel(aes(label = gene), data = subset(d, kind == "DE"),max.overlaps = 10,show.legend = F, min.segment.length = 0) + scale_y_continuous() +
    scale_color_manual(values = c('orange','forestgreen', 'red',  'black')) +
    labs(x = x, y = ylab, title = ttl) + theme(axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        legend.title = element_blank())
}
```

## Volcano
```{r echo = FALSE, warning=FALSE,message=FALSE, fig.cap="NSD1.KO is set as baseline/reference. Cutoff for DEGs: abs(FC) > 2 & padj < 0.05",out.width='100%'}
#How does NSD2-KO differ from NSD1-KO?
#resLFC_cal27_nsd1v2 <- lfcShrink(dds, contrast = c('group', 'Cal27NSD2.KO', 'Cal27NSD1.KO'), type = 'normal')
load("~/Documents/Q005841_HNSCC/data/rd_cal27_nsd1v2.RData")
#volcano plot
volc(rd_cal27,'log2FoldChange','padj','-log10(FDR)','')
```

## Pathway analysis - upregulated
```{r echo = FALSE, warning=FALSE,message=FALSE,out.width='100%'}
#pathway analysis
load("~/Documents/Q005841_HNSCC/data/cal27_pa.RData")

gostplot(cal27_pa$up,capped = FALSE,interactive = TRUE)
reactable(cal27_pa$up_reactable)
```

## Pathway analysis - downregulated
```{r echo = FALSE, warning=FALSE,message=FALSE,out.width='100%'}
gostplot(cal27_pa$down,capped = FALSE,interactive = TRUE)
reactable(cal27_pa$down_reactable)
```

## GSEA
```{r echo = FALSE, warning=FALSE,message=FALSE,out.width='100%'}
load("~/Documents/Q005841_HNSCC/data/cal27_nsd1v2_gsea.RData")
plot(cal27_nsd1v2_gsea$plot.r)
cal27_nsd1v2_gsea$gsea_table
```

## GSEA Top hit
```{r echo = FALSE, warning=FALSE,message=FALSE,out.width='100%'}
plot(cal27_nsd1v2_gsea$top_hit)
```

## {-}

---

# Cal27: comparison of NSD knockouts {.tabset .tabset-pills}

## Volcano
```{r echo = FALSE, warning=FALSE,message=FALSE,out.width='100%'}
cs <- c('Cal27NSD1.KO', 'Cal27NSD2.KO', 'Cal27NSD.DKO', 'Cal27NSD.TKO')
sclrs <- c(DE = 'forestgreen', 'FDR<0.05' = 'red', '|logFC|>2' = 'orange', 'NS' = 'black')
load("~/Documents/Q005841_HNSCC/data/nsd_comparisons.RData")
load("~/Documents/Q005841_HNSCC/data/colorsfor_nsdcomparisons.RData")
ggplot(pd, aes(x = log2FoldChange, y = -log10(padj))) +
  geom_point(aes(color = kind), size = 0.1, alpha = 0.7) +
  scale_color_manual(values = sclrs) +
  geom_richtext(aes(label = l), data = sts, x = 0, y = 35,size = 3) +
  facet_grid(c2 ~ c1) +
  xlab(expression(log[2]*FoldChange)) +
  ylab(expression(-log[10](p[adj]))) +
  coord_cartesian(ylim = c(0,60)) + geom_text_repel(aes(label = gene), data = subset(pd, kind == "DE"),max.overlaps = 5,show.legend = F, min.segment.length = 0,force = 0.1,force_pull = 0.1,size=1.5) +
  theme(legend.position = 'none',
        plot.background = element_blank(),
        panel.background = element_rect(fill = NA, color = 'black', size = 1),
        axis.text = element_text(color = 'black'),
        panel.grid = element_blank(),
        #axis.line = element_line(color = 'black'),
        panel.grid.major = element_line(color = 'grey90', linetype = 'dashed'),
        strip.background = element_rect(fill='black'),
        strip.text = element_text(color = 'white'),
        legend.title = element_blank(),
        legend.background = element_blank(),
        legend.key = element_blank())
```

## Overlap {.tabset}

### Odds ratio 
```{r echo = FALSE, warning=FALSE,message=FALSE,out.width='100%'}
load("~/Documents/Q005841_HNSCC/data/res_nsd_ko_comparisons.RData")
nums <- res %>%
  na.omit() %>%
  dplyr::filter(padj < .05) %>%
  mutate(s = case_when(log2FoldChange > 0 ~ sprintf('%s > %s', c1, c2),
                       log2FoldChange < 0 ~ sprintf('%s < %s', c1, c2)),
         d = case_when(log2FoldChange > 0 ~ '+',
                       log2FoldChange < 0 ~ '-')) %>%
  {split(.$ID, .$s)}
ugs <- unlist(nums) %>%
  unique() %>%
  length()
ors <- lapply(names(nums), function(x) {
  lapply(names(nums), function(y) {
    mm <- tibble(a = length(intersect(nums[[x]],nums[[y]]))) %>%
      mutate(b = length(nums[[x]]) - a,
             c = length(nums[[y]]) - a,
             d = ugs - a - b - c)
      
    matrix(unlist(mm), 2) %>%
      {mutate(tidy(fisher.test(., alternative = 'two.sided')),
              p = fisher.test(., alternative = 'greater')$p.value)} %>%
      dplyr::select(or = estimate, pb = p.value,
                    clo = conf.low, chi = conf.high, p) %>%
      mutate(c1 = x, c2 = y) %>%
      cbind(mm)
  }) %>% bind_rows()
}) %>% bind_rows() %>% as_tibble() %>% mutate(j = a / (a + b + c))
hms <- c('p','or','j') %>%
  setNames(., .) %>%
  lapply(function(x) {
    oo <- ors[,c('c1','c2',x)] %>%
      `colnames<-`(c('c1','c2','v'))
    if (x == 'p') {
      oo$v <- oo$v %>%
        {.[.==0] <- min(.[.!=0]);.} %>%
        log10() %>%
        {-.}
      oo %>%
        mutate(v = case_when(!is.finite(v)~NA_real_, T ~ v)) %>%
        pivot_wider(names_from = c2, values_from = 'v') %>%
        column_to_rownames('c1') %>%
        heatmaply()
    } else if (x == 'or') {
     
      oo$v <- log2(oo$v)
      oo$v[oo$v == -Inf] <- min(oo$v[is.finite(oo$v)])
      oo$v[oo$v == Inf] <- max(oo$v[is.finite(oo$v)])
      oo %>%
        mutate(v = case_when(!is.finite(v)~NA_real_, T ~ v)) %>%
        pivot_wider(names_from = c2, values_from = 'v') %>%
        column_to_rownames('c1') %>%
        heatmaply(scale_fill_gradient_fun = scale_fill_gradientn(
          colors = pals::coolwarm(10), limits = c(-5,5)))
    } else {
      oo %>%
        pivot_wider(names_from = c2, values_from = 'v') %>%
        column_to_rownames('c1') %>%
        heatmaply()
    }
  })
hms$or
```

### Fisher p-value
```{r echo=FALSE, message=FALSE, warning=FALSE,out.width='100%',fig.height=6}
hms$p
```

### Jaccard indices
```{r echo=FALSE, message=FALSE, warning=FALSE,out.width='100%',fig.height=6}
hms$j
```

### {-}